spring.application.name=backend
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/pwdb
spring.datasource.username=super
spring.datasource.password=super
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.security.user.name=none
spring.security.user.password=none
jwt.secret=super_secret_key_super_secret_key_123456
jwt.expiration=86400000
